# config/packages/security.yaml
security:
   
    encoders:
        App\Entity\User:
            algorithm: auto

    
    providers:
                # in_database:
                #     entity:
                #         class: App\Entity\User
                #         property: email
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: lazy

            guard:
                authenticators:
                    - App\Security\AdminAccountAuthenticator
            
            form_login:
                login_path: app_login
                check_path: app_login

            logout:
                path: app_logout
                target: homepage


        admin:
            pattern: ^/dashboard
            anonymous: true

                # main:
        #     anonymous: lazy
        #     guard:
        #         authenticators:
        #             - App\Security\AdminAccountAuthenticator
        #     logout:
        #         path: app_logout
        #         # where to redirect after logout
        #         # target: app_any_route

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, roles: ROLE_ADMIN }