# config/packages/security.yaml
security:
   
    encoders:
        App\Entity\User:
            algorithm: auto


    
    providers:
                # in_database:
                #     entity:
                #         class: App\Entity\User
                #         property: email
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        main:
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\AdminAccountAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
        