vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix: /images/product_images
            upload_destination: "%kernel.project_dir%/public/images/product_images"
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        
        reseaux_images:
            uri_prefix: /images/reseaux_images
            upload_destination: "%kernel.project_dir%/public/images/reseaux_images"
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        
        services_images:
            uri_prefix: /images/services_images
            upload_destination: "%kernel.project_dir%/public/images/services_images"
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        
        projets_images:
            uri_prefix: /images/projets_images
            upload_destination: "%kernel.project_dir%/public/images/projets_images"
            namer: Vich\UploaderBundle\Naming\UniqidNamer


